version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: k@123
      POSTGRES_DB: keshav
    
    volumes:
      - postgres-data:/var/lib/postgresql/data

  your-application:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres

volumes:
  postgres-data:
